### ISSUE TITLE
[Task] sequelize local 환경에서 테스트해보기

### ISSUE THREAD

**Issue by dankhan102** [codestates/exercisetoday#16]
### ISSUE
- Group:   `server`,
- Type:  `test`
- Detail: sprint ORM 복습, sequelize join table 형성 (공식문서) 

### TODO
1. [x] MVC model 구현
2. [x] 1:N 관계 sequelize로 구현
3. [x] N:N 관계 sequelize로 구현 

### Labels
- Estimated time: `E: 5h`
- Group :  `server`
- Sprint: `Sprint2`
- Urgency: `High`
