### ISSUE TITLE
[Task] 데이터베이스에 넣을 기본 데이터 틀 만들기

### ISSUE THREAD

**Issue by spirited-hunger** [codestates/exercisetoday#56]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: Sequelize 로 seed 생성하기위한 마이그레이션 스켈레톤 만들기

### TODO
1. [x] 로컬에 mysql 데이터베이스 생성
2. [x] 데이터베이스에 sequelize 로 테이블 생성
3. [x] 테이블간 관계설정
4. [x] seed 생성용 마이그레이션 스켈레톤 생성
5. [x] seed 생성하고 관계이용해서 데이터 가져오기

### Labels
- Estimated time: `E: 5h`
- Group :  `server`
- Sprint: `Sprint 2`
- Urgency: `High`
