### ISSUE TITLE
[Task] sequelize DB 구현

### ISSUE THREAD

**Issue by dankhan102** [codestates/exercisetoday#97]
### ISSUE
- Group:   `server`
- Type:  `feature`
- Detail: sequelize로 DB와 server 연결

### TODO
1. [x] sequelize model 생성
2. [x] sequelize table간 constraint 연결
3. [x] seed file 생성

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 1d`
- Group :  `server`
- Sprint: `Sprint3`
- Urgency: `High`
